### ISSUE TITLE
Parsing projects with multiple remake files (recursive remake)

### ISSUE THREAD

**Issue by dfalster** [wlandau/parallelRemake#2]
Out of interest, I tried to run parallelRemake to [this project](https://github.com/dfalster/baad) with several remake files and ran into errors. The program executes fine and generates a nice makefile, but it is not catching the second file with additional targets. Note the extra files [remake_data](https://github.com/dfalster/baad/blob/master/remake_data.yml) and [remake_reports.yml](https://github.com/dfalster/baad/blob/master/remake_reports.yml) listing additional targets. These files are [sourced from the main remake file](https://github.com/dfalster/baad/blob/master/remake.yml#L16). Recursive files like this are a standard feature for remake (e.g. [see tests](https://github.com/richfitz/remake/blob/bcf0a504f80ea0541a65e253f8aa511c9bf606eb/tests/testthat/test-remake.R#L3)) so perhaps worth supporting?

**Comment by wlandau** [comment]
Yup, that's important. I just committed an update, and your project ran for me without a hitch. I'm not familiar with the exact details of [`baad`](https://github.com/dfalster/baad), but `make -j 8` completed normally without warnings or errors.

For the case of a single remake file, nothing has changed, Otherwise, `write_makefile` now combines all the remake files into a single one (in your case, "collated_remake.yml"). The Makefile then uses `collated_remake.yml`. Collation happens recursively, so all the dependencies in "include:" and the dependencies of those files, etc., are included.

**Comment by dfalster** [comment]
Nice!
